---
# Core Configuration
# https://esphome.io/components/esphome.html
esphome:
  name: esphome-web-e45ce4
  friendly_name: MYPV ELWA Heizstab

# ESP32 Configuration
# https://esphome.io/components/esp32.html
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
# https://esphome.io/components/api.html
# api:
#   encryption:
#     key: !secret api_encryption_key

# Connect MQTT client to a MQTT broker
# https://esphome.io/components/mqtt.html#mqtt-component-base-configuration
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: heizstab

# Enable Over-the-Air Updates
# https://esphome.io/components/ota/
ota:
  - platform: esphome

# WiFi Configuration
# Connect your device to your wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Configure a static IP address (optional)
  # manual_ip:
  #   static_ip: 192.168.178.100
  #   gateway: 192.168.178.1
  #   subnet: 255.255.255.0
  #   dns1: 8.8.8.8
  #   dns2: 8.8.4.4

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Esphome-Web-E45CE4'
    password: !secret wifi_ap_password

# Enable a captive portal
captive_portal:

# Enable a webserver on port 80
web_server:
  port: 80

# -------------------------------------------------------------------------
# ------------------CODE-FOR-GETTING-SERIAL-ELWA_DC-DATA-------------------
# -------------------------------------------------------------------------

logger:
  baud_rate: 9600
  logs:
    component: ERROR

text_sensor:
  - platform: template
    id: device_reply
    name: 'Geräteantwort'
  - platform: template
    id: firmware_version
    name: 'Firmware-Version'

binary_sensor:
  - platform: template
    id: dc_disconnect
    name: 'DC-Trennung'

  - platform: template
    id: dc_relay
    name: 'DC-Relais'

  - platform: template
    id: ac_relay
    name: 'AC-Relais'

  - platform: template
    id: lower_position
    name: 'Untere Position'

sensor:
  - platform: template
    id: operating_days
    name: 'Betriebstage'
    unit_of_measurement: 'd'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: mpp_status
    name: 'MPP-Status'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: water_temperature
    name: 'Wassertemperatur'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: never
    filters:
      - multiply: 0.1

  - platform: template
    id: temperature_min
    name: 'Minimale Temperatur'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: never
    filters:
      - multiply: 0.1

  - platform: template
    id: temperature_max
    name: 'Maximale Temperatur'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: never
    filters:
      - multiply: 0.1

  - platform: template
    id: target_temperature_pv
    name: 'Zieltemperatur PV'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: never
    filters:
      - multiply: 0.1

  - platform: template
    id: target_temperature_grid
    name: 'Zieltemperatur Netz'
    unit_of_measurement: '°C'
    device_class: 'temperature'
    state_class: 'measurement'
    accuracy_decimals: 1
    update_interval: never
    filters:
      - multiply: 0.1

  - platform: template
    id: device_temperature
    name: 'Gerätetemperatur'
    unit_of_measurement: '°C'
    update_interval: never

  - platform: template
    id: insulation_measurement
    name: 'Isolationsmessung'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: fault_code
    name: 'Fehlercode'
    update_interval: never

  - platform: template
    id: input_voltage
    name: 'Eingangsspannung'
    unit_of_measurement: 'V'
    device_class: 'voltage'
    state_class: 'measurement'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: input_current
    name: 'Eingangsstrom'
    unit_of_measurement: 'A'
    device_class: 'current'
    state_class: 'measurement'
    update_interval: never
    accuracy_decimals: 2

  - platform: template
    id: power_now
    name: 'Aktuelle Leistung'
    unit_of_measurement: 'W'
    device_class: 'power'
    state_class: 'measurement'
    update_interval: never

  - platform: template
    id: energy_today
    name: 'Energie heute'
    unit_of_measurement: 'kWh'
    device_class: 'energy'
    state_class: 'total'
    update_interval: never
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: template
    id: energy_total
    name: 'Gesamtenergie'
    unit_of_measurement: 'kWh'
    device_class: 'energy'
    state_class: 'total_increasing'
    update_interval: never
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: template
    id: grid_energy_today
    name: 'Netzenergie heute'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: grid_energy_total
    name: 'Netzenergie gesamt'
    update_interval: never

  - platform: template
    id: unknown_22
    name: 'Unbekannt 22'
    update_interval: never

  - platform: template
    id: unknown_23
    name: 'Unbekannt 23'
    update_interval: never

  - platform: template
    id: unknown_24
    name: 'Unbekannt 24'
    update_interval: never

  - platform: template
    id: runtime_today
    name: 'Laufzeit heute'
    unit_of_measurement: 'min'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: grid_charge_start
    name: 'Netzladestart'
    update_interval: never

  - platform: template
    id: serial_number
    name: 'Seriennummer'
    update_interval: never
    accuracy_decimals: 0

  - platform: template
    id: unknown_29
    name: 'Unbekannt 29'
    update_interval: never

  - platform: template
    id: unknown_30
    name: 'Unbekannt 30'
    update_interval: never

  # - platform: template
  #   id: Token_31
  #   name: "Status"
  #   update_interval: never

uart:
  - id: uart_elwa
    baud_rate: 9600
    rx_buffer_size: 1024
    tx_pin: 17
    rx_pin: 16
    debug:
      direction: RX
      dummy_receiver: true
      # after:
      # delimiter: "\r\n"
      # delimiter: "\t"
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);           // Log UART data
            std::string str(bytes.begin(), bytes.end());       // Convert bytes to string

            // Check if the content of the string is not equal to "rs\r\n"  =>  starts with "ds\r\n"
            if (str != "rs\r\n") {
                std::vector<std::string> tokens;               // Vector to store extracted tokens
                size_t start_index = 0;                        // Index to keep track of the start position while extracting tokens

                // Extract tokens from the string
                while (start_index < str.size()) {
                    size_t end_index = start_index;
                    while (end_index < str.size() && str[end_index] != '\t') {
                        end_index++;
                    }
                    // Push the extracted token into the vector
                    tokens.push_back(str.substr(start_index, end_index - start_index));
                    if (end_index < str.size() && str[end_index] == '\t') {
                        end_index++; // Move past the tab character
                    }
                    start_index = end_index;
                }


                const std::vector<std::function<void(const std::string&)>> handlers = {
                    [](const std::string &v){ id(device_reply).publish_state(v.c_str()); },
                    [](const std::string &v){ id(firmware_version).publish_state(v.c_str()); },
                    [](const std::string &v){ id(operating_days).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(mpp_status).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(dc_disconnect).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(dc_relay).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(ac_relay).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(water_temperature).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(temperature_min).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(temperature_max).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(target_temperature_pv).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(target_temperature_grid).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(device_temperature).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(insulation_measurement).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(fault_code).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(input_voltage).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(input_current).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(power_now).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(energy_today).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(energy_total).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(grid_energy_today).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(grid_energy_total).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(unknown_22).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(unknown_23).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(unknown_24).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(runtime_today).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(grid_charge_start).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(lower_position).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(serial_number).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(unknown_29).publish_state(atof(v.c_str())); },
                    [](const std::string &v){ id(unknown_30).publish_state(atof(v.c_str())); }
                    // [](const std::string &v){ id(Token_31).publish_state(atof(v.c_str())); }
                };

                for (size_t i = 0; i < tokens.size(); i++) {
                    ESP_LOGD("main", "Token %d: %s", i, tokens[i].c_str());
                    if (i < handlers.size()) {
                        handlers[i](tokens[i]);
                    } else {
                        ESP_LOGW("main", "Unhandled token %d with value %s", i, tokens[i].c_str());
                    }
                }
                if (tokens.size() != handlers.size()) {
                    ESP_LOGW("main", "Token count mismatch: received %d tokens, expected %d", tokens.size(), handlers.size());
                }
            } else {
                // Handle the case where the content of str is "rs\r\n"  =>  ElwaDC is off due to drop of PV input voltage below threshold
                // id(Token_15).publish_state(0);  // set voltage to zero
                // id(Token_16).publish_state(0);  // set current to zero
                // id(Token_17).publish_state(0);  // set power to zero
            }

# ----------------------CODE-TO-REQUEST-ELWA_DC-SERIAL-DATA----------------------

# if you need to send a request periodically to get response from the uart device
interval:
  - interval: 20s  # interval to request measurements
    then:
      # request for getting all relevant token values 'rs'
      - uart.write: [0x72, 0x73, 0x0D, 0x0A]
      # "ping" request for getting just an OK
      # - uart.write:  [0x72, 0x72, 0x71, 0x0D, 0x0A]
